[package]
name = "uow"
version = "0.1.0"
entrypoint = "lib/lib.typ"
authors = ["The Typst Project Developers"]
license = "MIT"
description = "Functions and Templates used for writing theses and assignments at UoW"

[template]
path = "template"
entrypoint = "template/main.typ"
thumbnail = "thumbnail.png"
